name: Update README.md

on:
  schedule:
    - cron: '0 0 * * *' # runs at 00:00 UTC every day
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update profile README

    steps:
      - uses: actions/checkout@v2
      - uses: Readme-Workflows/recent-activity@v2.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
